export const comments = [
  {
    name: "Alex Johnson",
    image: "https://i.pravatar.cc/150?img=10",
    comment: "This video was incredibly helpful! Thanks for sharing.",
    date: "2025-09-07T14:35:00Z",
    likes: 124,
    dislikes: 2,
    isHearted: true,
    replies: [
      {
        name: "Mia Chen",
        image: "https://i.pravatar.cc/150?img=47",
        comment: "Agreed! Especially the part about async functions.",
        date: "2025-09-07T15:00:00Z",
        likes: 45,
        dislikes: 1,
        isHearted: false,
        replies: [
          {
            name: "Devon King",
            image: "https://i.pravatar.cc/150?img=12",
            comment: "Yeah, that made it so much clearer.",
            date: "2025-09-07T15:20:00Z",
            likes: 17,
            dislikes: 0,
            isHearted: false,
            replies: [
              {
                name: "Ravi Patel",
                image: "https://i.pravatar.cc/150?img=23",
                comment: "Honestly I had to rewatch that part twice 😅",
                date: "2025-09-07T15:30:00Z",
                likes: 12,
                dislikes: 0,
                isHearted: false,
                replies: [
                  {
                    name: "Sophie Lee",
                    image: "https://i.pravatar.cc/150?img=29",
                    comment: "Same here — worth the rewatch though!",
                    date: "2025-09-07T15:45:00Z",
                    likes: 8,
                    dislikes: 0,
                    isHearted: false,
                    replies: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Jordan Fields",
    image: "https://i.pravatar.cc/150?img=35",
    comment: "Can someone explain the setup at 03:14?",
    date: "2025-09-08T09:00:00Z",
    likes: 20,
    dislikes: 0,
    isHearted: false,
    replies: [
      {
        name: "Taylor Morgan",
        image: "https://i.pravatar.cc/150?img=17",
        comment: "It's just the initial config for Firebase auth.",
        date: "2025-09-08T09:10:00Z",
        likes: 11,
        dislikes: 0,
        isHearted: false,
        replies: [],
      },
    ],
  },
  {
    name: "Priya Desai",
    image: "https://i.pravatar.cc/150?img=42",
    comment: "I love how well-structured this tutorial is 🙌",
    date: "2025-09-06T18:10:00Z",
    likes: 76,
    dislikes: 1,
    isHearted: true,
    replies: [],
  },
];
